import { Button, VerticalBox, HorizontalBox, TextEdit } from "std-widgets.slint";
import { Toolbar } from "components/Toolbar.slint";

export component PDFViewer inherits Window {
	in-out property <string> textContent;
	in-out property <int> pageCount: 0;
	
	VerticalBox {
		spacing: 0px;
		padding: 0px;

		toolBar := Toolbar {
			currentPage: 1;
			pages: root.pageCount;
			zoom: 1.0;

			height: 40px;
		}

		textEdit := TextEdit {
			min-height: 200px;
			text: root.textContent;
		}
	}
}
