# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "PDFViewer"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
getrandom = { version = "0.2.2", features = ["js"] }

[lib]
path = "src/main.rs"
crate-type = ["cdylib"]

[dependencies]
slint = "1.14.1"
lopdf = { version = "0.33", default-features = false, features = ["pom_parser"] }

[build-dependencies]
slint-build = "1.14.1"
